# Server Port (Cloud platforms provide PORT dynamically)
server.port=${PORT:8080}

# Spring Data JPA & MySQL (Environment Variables for Production)
spring.datasource.url=${jdbc:mysql://mysql-6199fe9-atharvakadam772-fc62.i.aivencloud.com:${20600}/${defaultdb}?sslmode=require}
spring.datasource.username=${avnadmin}
spring.datasource.password=${AVNS_yArbjITDI6c3nPDYqwv}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OpenAPI / Swagger Path
springdoc.swagger-ui.path=/swagger-ui.html